name: Simple CI

on:
 push:
 pull_request:
 branches: main

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: docker build -t sali .
      
      - name: Syntax Check
        # This checks if the file is valid JavaScript without actually running the server
        run: docker run -d -p 3000:3000 --name sali0 sali
