name: Simple CI

on: [push]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install axios

      - name: Install
        run: npm install check-disk-space

      - name: Install
        run: npm install
      
      - name: Syntax Check
        # This checks if the file is valid JavaScript without actually running the server
        run: npm start